{% set version = "3.3.0" %}

package:
  name: redis-py
  version: {{ version }}

source:
  url: https://github.com/andymccurdy/redis-py/archive/{{ version }}.tar.gz
  sha256: 580920a17c4661996516a484922252810977fe1d95eb2e43e629136401b35e76

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - redis
  requires:
    - pytest >=2.5.0

about:
  home: https://github.com/andymccurdy/redis-py/
  license: MIT
  license_url: https://github.com/andymccurdy/redis-py/blob/master/LICENSE
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Redis key-value store
  description: |
    The Python interface to the Redis key-value store. Requires a running
    Redis server.
  doc_url: https://pypi.python.org/pypi/redis
  doc_source_url: https://github.com/andymccurdy/redis-py/blob/master/README.rst
  dev_url: https://github.com/andymccurdy/redis-py/

extra:
  recipe-maintainers:
    - kwilcox
    - daf
