{% set name = "redis-py" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/redis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 81c2b08d544f101c22adc15277704d5dde23dabab91a6bb3b993b0b659d418b2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - async-timeout >=4.0.3 # [py<312]
  run_constrained:
    - hiredis >=3.0.0
    - cryptography >=36.0.1
    - requests >=2.31.0
    - pyopenssl >=23.2.1

test:
  commands:
    - pip check
  imports:
    - redis
    - redis.asyncio
    - redis.commands
    - redis.commands.bf
    - redis.commands.json
    - redis.commands.search
    - redis.commands.timeseries
    - redis.commands.graph
  requires:
    - pip

about:
  home: https://github.com/redis/redis-py/
  license: MIT
  license_url: https://github.com/redis/redis-py/blob/master/LICENSE
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Redis key-value store
  description: |
    The Python interface to the Redis key-value store. Requires a running
    Redis server.
  doc_url: https://pypi.python.org/pypi/redis
  doc_source_url: https://github.com/redis/redis-py/blob/master/README.md
  dev_url: https://github.com/redis/redis-py/
extra:
  recipe-maintainers:
    - kwilcox
    - daf
