{% set version = "5.2.0" %}

package:
  name: redis-py
  version: {{ version }}

source:
  url: https://github.com/redis/redis-py/archive/v{{ version }}.tar.gz
  sha256: 9be14a8c988a0428c942b8eda201bb2ed2ea6ff7c05a07bbede45b1e1b60d19c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - async-timeout >=4.0.3 # [py<312]
  run_constrained:
    - hiredis >=3.0.0
    - cryptography >=36.0.1
    - requests >=2.31.0

test:
  commands:
    - pip check
  imports:
    - redis
    - redis.asyncio
    - redis.commands
    - redis.commands.bf
    - redis.commands.json
    - redis.commands.search
    - redis.commands.timeseries
    - redis.commands.graph
  requires:
    - pip

about:
  home: https://github.com/redis/redis-py/
  license: MIT
  license_url: https://github.com/redis/redis-py/blob/master/LICENSE
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Redis key-value store
  description: |
    The Python interface to the Redis key-value store. Requires a running
    Redis server.
  doc_url: https://pypi.python.org/pypi/redis
  doc_source_url: https://github.com/redis/redis-py/blob/master/README.md
  dev_url: https://github.com/redis/redis-py/
extra:
  recipe-maintainers:
    - kwilcox
    - daf
