travis:
  secure:
    BINSTAR_TOKEN: CNgUTB6sItqIZN5rElzpFrm7RauoNoxF7YRbmuuBCcql/Oe0121iEVIts8XM7mCKWLVs05KvpOTECriCAeeJzQDZ14qdNtSpd2wKw63BFgMDtW5bJBUECluTsXpkgaCFOgQbjs0+f4eRKI2hV7X1+1U8xsZJy9GmYMjIR0hRjTO/7Si0uSnS6YdIY/RuhOIQ/JnRYxZU4xk49Jp3bQ4mtDgupwME7H9GNi5peKaqMfHCyy7VgVPJQD1xFnyEyrIF1QZkmfGm1M1clvB0aNSJaez5Ubsgz1RhLHJj+TCN/J1e84soua+IAWHLyqXyA0ARCla1wI1S3YfXtwLXY756+dnyBb67TDzVNcaDdnd2K95fkjblgS2mD32Z78TbkSgUlQefsi27N78p+BROhyYNkgY5Cg6/iv/Yoy7LFgQvZB8ER9n9NBsme2UJLpd+Nu4KOG/9nFK2FQBA8WgPYXweu7IKbb88Ilnj4nE9ZIbnAZVFdCLBAatmdGymq+hFu5pl+ffYzU2x9xMPy8VOGheTU56BhyVF1ElwVj8UJTv/rDL+bxZLepqUuhZQKeoOqAjWrsVD5LUCpwkBcCfXJ9UeAys9GWYtcBdvQAYvdkLCoMp8RFbsz6cSnBd/gJNiauf/hrZTBJ1OPaaP412Q3B9W765MzWQB6TqV1t73fVhTfgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
