travis:
  secure:
    BINSTAR_TOKEN: a/gx5Ij6e4kAWbdlEmqKceErHXPkCEBCf2A12c8kV9/6gJ3i/v4WdwPVzMA6ks8Tr5F0eXUKDk8+EFs9SMgicnjcsnveoCJB0Ol0Vs8TyTPjdTXt1yHETGN9ncz+69b9iOEJShn8H+xZuifXHZXKEklzW4kH4uRMkKLht2PHprqMzGhRYtDMsNe8QqImVAclc8I74M6qn8z49aytchohIlBWrOVleDJ7lIUTVxGDysrhdp5UwFHVDRkv0UdceXZaFCSECm/jpfltygM2St072Yv+3BNbXtbjhR5S7T5iEpSuveJO8TflhJm4LezVkZBllp26PWy62ESG7ETQAqMxST7XOoI2ykEGhPn2uTwwFbSr+v2XA20vv6CHjDHx4RyaG2uaZ/4T5ARFyGno/CUOxJBmOhDh6qGyCowG+WXVLnH+x7PAagAVPirRcHWtbgXFujfaI3dFg1k4qDkdxOMsVQ3c5Z56OsmylCjMq6FJvISi829hRgSo2I6xK9O/+9J3rGY4mCz0k97l4S2FDSSqm2BAnk7Bf03pjF19kU0KeAE1XpxyM8+3sWZAAXUHuNmF8/z7bgrycNhLj5tTCBfbFDckI2usjpx/0B7w4pup0AbPRoPBfMGFSpf7icxj/nSc2B83Dl60w06QrqF2TtDboq1mFxwGf0f7ESYuSExDWiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
