travis:
  secure:
    BINSTAR_TOKEN: PEpU4ZaLPd6JamFkutzb6sXRFRZSffYcpenyIaxmZKENMpXQwBGiOFRELPkSWWFxSz35M4mflP3yeuZb0URjjZDSSv7MwNVqZQl4+SAsidKt2LW5e/MDEn1nL5Zvuvriykc5jRwgOIsXSKdCNHjg2g37z5Wl4SC6To+aFVpcb9q3KYH5lF2T2AhSXa+JHg4F2s8b2kGn7/IJU70lIoHeReT8mHX4vDaODevj6wxtJjSOKT3ozLu+p3w4IxDJYSiwqTpL29HPBivMtizW2jyBECv9mzJIRqap6uhsbKWzs9DgOmPxoj8p22UTO7fKaMSqEfCuJQMLt3OiywcICQmfYJHvciGYzTcDt4ZIzi672ck3p/KixF0bsPEm15nSIUQyqEYD2xoR5JqhZA7SNySkkjtpS77zZeLK1h3NM0WpJkZbj3Vf84wBynxd8OwWWo7InlnV5z5GZHMowHdmIKr5bsFn+OiTRM8JRCUMMvDcuDlAny4/VqWPHD4qf9SWrPezFLvxuhlenpX56s5ZVGka2NE+k+ec+HsL5qW4OXML7NOA4L5+4lWCv+UQTWTrdeVL1wp00D7NrJcVtUfGk8AtS6v013QWYEA8Hbstfihy7w2cEXI+O27etfv+gQ5MxvCq1CenAEinrNVIkQCtusq8tGiNv5wwobPabYeKxMY2Sls=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
